name: build-v5

on:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:
      runtimeBranch:
        description: Branch for runtime repository
        required: true
        default: 'v5.0.9'
      aspBranch:
        description: Branch for aspnetcore repository
        required: true
        default: 'v5.0.9'
      installerBranch:
        description: Branch for installer repository
        required: true
        default: 'v5.0.400'


concurrency:
  group: action-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  runtime:
    name: Runtime

    runs-on: 'ubuntu-20.04'

    steps:
      - uses: actions/checkout@v2
        with:
          path: dotnet-bsd
      - uses: actions/checkout@v2
        with:
          repository: dotnet/runtime
          ref: ${{ github.event.inputs.runtimeBranch }}
          path: runtime
      - run: |
          git -C runtime checkout ${{ github.event.inputs.runtimeBranch }}
          sed -i '/\/dnceng\/internal\//d' runtime/NuGet.config
      - run: |
          DOTNET_DOCKER_TAG="mcr.microsoft.com/dotnet-buildtools/prereqs:$(curl -s https://raw.githubusercontent.com/dotnet/versions/master/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json | jq -r '.repos[0].images[] | select(.platforms[0].dockerfile | contains("freebsd/11")) | .platforms[0].simpleTags[0]')"
          echo $DOTNET_DOCKER_TAG
          docker run -e ROOTFS_DIR=/crossrootfs/x64 -v ${GITHUB_WORKSPACE}/runtime:/runtime $DOTNET_DOCKER_TAG /runtime/build.sh -ci -c Release -cross -os freebsd /p:BuildNumberMajor=21102 /p:BuildNumberMinor=12 /p:OfficialBuildId=20210202.12 /p:IsEligibleForNgenOptimization=false
      - name: Publish Runtime
        uses: actions/upload-artifact@v2
        with:
          name: RuntimePackages
          path: runtime/artifacts/packages/Release/Shipping

  aspnetcore:
    name: AspNetCore
    needs: runtime

    runs-on: 'ubuntu-20.04'

    steps:
      - uses: actions/checkout@v2
        with:
          path: dotnet-bsd
      - uses: actions/checkout@v2
        with:
          repository: dotnet/aspnetcore
          ref: ${{ github.event.inputs.aspBranch }}
          path: aspnetcore
      - run: |
          git -C aspnetcore checkout ${{ github.event.inputs.aspBranch }}
          sed -i '/linux-x64;/a \ \ \ \ \ \ freebsd-x64;' aspnetcore/Directory.Build.props
          sed -i '/<LatestPackageReference Include="Microsoft.NETCore.App.Runtime.linux-x64" \/>/a \ \ \ \ <LatestPackageReference Include="Microsoft.NETCore.App.Runtime.freebsd-x64" \/>' aspnetcore/eng/Dependencies.props
          dotnet nuget add source ../runtime/artifacts/packages/Release/Shipping --name local --configfile aspnetcore/NuGet.config
          sed -i '/\/dnceng\/internal\//d' aspnetcore/NuGet.config
      - uses: actions/download-artifact@v2
        with:
          name: RuntimePackages
          path: runtime/artifacts/packages/Release/Shipping
      - run: |
          ls -lR runtime
          mkdir -p aspnetcore/artifacts/obj/Microsoft.AspNetCore.App.Runtime
          cp runtime/artifacts/packages/Release/Shipping/dotnet-runtime-*-freebsd-x64.tar.gz aspnetcore/artifacts/obj/Microsoft.AspNetCore.App.Runtime
          aspnetcore/build.sh -c Release -ci --os-name freebsd -pack -nobl /p:CrossgenOutput=false /p:OfficialBuildId=$(date +%Y%m%d)-99
      - name: Publish AspNetCore Packages
        uses: actions/upload-artifact@v2
        with:
          name: AspNetCorePackages
          path: aspnetcore/artifacts/packages/Release/Shipping
      - name: Publish Runtime
        uses: actions/upload-artifact@v2
        with:
          name: AspNetCoreInstallers
          path: aspnetcore/artifacts/installers/Release

  installer:
    name: Installer
    needs: aspnetcore

    runs-on: 'ubuntu-20.04'

    steps:
      - uses: actions/checkout@v2
        with:
          path: dotnet-bsd
      - uses: actions/checkout@v2
        with:
          repository: dotnet/installer
          ref: ${{ github.event.inputs.installerBranch }}
          path: installer
      - run: |
          git -C installer checkout ${{ github.event.inputs.sdkBranch }}
          git -C installer apply ../dotnet-bsd/patches/installer/0001-freebsd-support.patch
          sed -i 's/NetCore5AppHostRids Include="@(NetCore31RuntimePackRids)/NetCore5AppHostRids Include="@(NetCore31RuntimePackRids);freebsd-x64/' installer/src/redist/targets/GenerateBundledVersions.targets
          sed -i 's/AspNetCore50RuntimePackRids Include="@(AspNetCore31RuntimePackRids)/AspNetCore50RuntimePackRids Include="@(AspNetCore31RuntimePackRids);freebsd-x64/' installer/src/redist/targets/GenerateBundledVersions.targets
          dotnet nuget remove source msbuild --configfile installer/NuGet.config || true
          dotnet nuget remove source nuget-build --configfile installer/NuGet.config || true
          dotnet nuget add source ../runtime/artifacts/packages/Release/Shipping --name runtime --configfile installer/NuGet.config
          dotnet nuget add source ../aspnetcore/artifacts/packages/Release/Shipping --name aspnetcore --configfile installer/NuGet.config
          sed -i '/\/dnceng\/internal\//d' installer/NuGet.config
      - uses: actions/download-artifact@v2
        with:
          name: RuntimePackages
          path: runtime/artifacts/packages/Release/Shipping
      - uses: actions/download-artifact@v2
        with:
          name: AspNetCorePackages
          path: aspnetcore/artifacts/packages/Release/Shipping
      - uses: actions/download-artifact@v2
        with:
          name: AspNetCoreInstallers
          path: aspnetcore/artifacts/installers/Release
      - run: |
          ls -lR runtime
          ls -lR aspnetcore
          mkdir -p installer/artifacts/obj/redist/Release/downloads/
          cp runtime/artifacts/packages/Release/Shipping/dotnet-runtime-*-freebsd-x64.tar.gz installer/artifacts/obj/redist/Release/downloads/
          cp aspnetcore/artifacts/installers/Release/aspnetcore-runtime-* installer/artifacts/obj/redist/Release/downloads/
          installer/build.sh -c Release -ci  -pack -nobl --runtime-id freebsd-x64 /p:OSName=freebsd /p:CrossgenOutput=false /p:OfficialBuildId=$(date +%Y%m%d)-99 /p:DISABLE_CROSSGEN=True /p:IncludeAspNetCoreRuntime=True
      - name: Publish Installer
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: installer/artifacts/packages/Release/Shipping
